In [2]:
import pandas as pd
import numpy as np
from numpy.linalg import norm

In [3]:
sentences = ["she wore a dress and red earrings",
            "the dress has a red wine stain",
            "tomorrow I will wear my new red dress",
            "the red dress in the photo resembles the red dress she is wearing",
            "short dress",
            "red lipstick"]

query = "red dress"

sentencesAndQuery = list(sentences)
sentencesAndQuery.append(query)

In [4]:
wordLists = [x.split() for x in sentencesAndQuery]
allWords = [i for row in wordLists for i in row]
len(allWords)

41

In [5]:
def createColForD(sentences,allWords):
    inSentence = {"d":['d1','d2','d3','d4','d5','d6','q']}
    
    for w in allWords:
        w_val = 0
        inSentence[w] = []
        
        for s in sentences:
            w_val = s.count(w)
            #print(w_val)
            inSentence[w].append(w_val)
                
    return inSentence

In [6]:
df = pd.DataFrame(createColForD(sentencesAndQuery,allWords)).set_index(['d'])
df

,she,wore,a,dress,and,red,earrings,the,has,wine,...,wear,my,new,in,photo,resembles,is,wearing,short,lipstick
d,,,,,,,,,,,,,,,,,,,,,
d1,1,1,3,1,1,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
d2,0,0,3,1,0,1,0,1,1,1,...,0,0,0,2,0,0,0,0,0,0
d3,0,0,1,1,0,1,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
d4,1,0,1,2,0,2,0,3,0,0,...,1,0,0,2,1,1,1,1,0,0
d5,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
d6,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
q,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
def cosineSimilarity(vec1,vec2):
    V1 = np.array(vec1)
    V2 = np.array(vec2)
    cosine = np.dot(V1,V2)/(norm(V1)*norm(V2))
    return cosine

In [8]:
queryVec = df.loc['q'].to_list()
tups = []

for i,s in enumerate(sentences):
    df_index = i+1
    sVec = df.loc[f"d{df_index}"].to_list()
    tups.append((cosineSimilarity(queryVec,sVec),s))

sorted_tuple = sorted(tups, key=lambda x: x[0],reverse=True)
sorted_tuple

[(0.5345224838248487,
  'the red dress in the photo resembles the red dress she is wearing'),
 (0.4999999999999999, 'short dress'),
 (0.4999999999999999, 'red lipstick'),
 (0.4714045207910316, 'tomorrow I will wear my new red dress'),
 (0.35355339059327373, 'she wore a dress and red earrings'),
 (0.32444284226152503, 'the dress has a red wine stain')]